export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/NJUST-AI/NJUST_AI_CJ",
	GITHUB_DISCUSSIONS: "https://github.com/NJUST-AI/NJUST_AI_CJ/discussions",
	DISCORD: "https://discord.gg/njust-ai-cj",
	REDDIT: "https://reddit.com/r/NJUST_AI_CJ",
	X: "https://x.com/roocode",
	LINKEDIN: "https://www.linkedin.com/company/roo-code",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/roocode.bsky.social",
	YOUTUBE: "https://www.youtube.com/@NJUST_AI_CJYT",
	DOCUMENTATION: "https://docs.njust-ai-cj.local",
	SLACK_DOCS: "https://docs.njust-ai-cj.local/roo-code-cloud/slack-integration",
	CAREERS: "https://careers.njust-ai-cj.local",
	ISSUES: "https://github.com/NJUST-AI/NJUST_AI_CJ/issues",
	FEATURE_REQUESTS: "https://github.com/NJUST-AI/NJUST_AI_CJ/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/NJUST-AI/NJUST_AI_CJ/discussions",
	CHANGELOG: "https://github.com/NJUST-AI/NJUST_AI_CJ/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/NJUST-AI/NJUST_AI_CJ/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.njust-ai-cj.local/community",
	TUTORIALS: "https://docs.njust-ai-cj.local/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.njust-ai-cj",
	SECURITY: "https://trust.njust-ai-cj.local",
	EVALS: "https://njust-ai-cj.local/evals",
	BLOG_SUBSTACK: "https://blog.njust-ai-cj.local",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@NJUST_AI_CJYT/podcasts",
	FAQ: "https://njust-ai-cj.local/#faq",
	TESTIMONIALS: "https://njust-ai-cj.local/#testimonials",
	CLOUD_APP_LOGIN: "",
	CLOUD_APP_SIGNUP: "",
	CLOUD_APP_SIGNUP_HOME: "",
	CLOUD_APP_SIGNUP_PRO: "",
	CLOUD_APP_TEAM_TRIAL: "",
	SUPPORT: "mailto:support@njust-ai-cj.local",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
